server.port = 5200
hc.storage.dir = ${HC_STORAGE_DIR:./storage}
hc.storage.public-base = http://localhost:5200
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB
